Repository watergis/maplibre-gl-terradraw, pull requests merged in 2024-11, with the labels that each got.

#56 remove controlContainer on map.removeControl(drawControl)
  .changeset/mighty-zebras-complain.md
  src/lib/MaplibreTerradrawControl.ts
Labels: bug

#59 feat: added Sensor mode and Sector mode to the plugin.
  .changeset/rare-planets-tell.md
  src/lib/constants/AvailableModes.ts
  src/lib/constants/defaultControlOptions.ts
  src/lib/constants/getDefaultModeOptions.ts
  src/lib/interfaces/TerradrawModeClass.ts
  src/routes/+layout.svelte
  src/routes/demo/+page.svelte
  src/scss/maplibre-gl-terradraw.scss
  static/assets/maplibre-npm-example.txt
  static/index_cdn.html
  vite.config.ts
Labels: enhancement

#61 call TerraDraw.stop() when calling onRemove()
  .changeset/kind-radios-fix.md
  src/lib/MaplibreTerradrawControl.ts
Labels: bug

#63 chore: updated dependencies
  package.json
  pnpm-lock.yaml
Labels: documentation

#64 doc: make demo page customisation available by selecting modes and open option in landing page
  src/routes/+page.server.ts
  src/routes/+page.svelte
  src/routes/demo/+page.svelte
  static/assets/maplibre-cdn-example.txt
  static/assets/maplibre-npm-example.txt
Labels: documentation

#65 feat: add mode to allow users to delete only selected feature.
  .changeset/friendly-vans-hammer.md
  src/lib/MaplibreTerradrawControl.ts
  src/lib/constants/AvailableModes.ts
  src/lib/constants/defaultControlOptions.ts
  src/lib/constants/getDefaultModeOptions.ts
  src/scss/maplibre-gl-terradraw.scss
Labels: enhancement

#72 Fix/svg icons
  .changeset/great-otters-drive.md
  package.json
  pnpm-lock.yaml
  src/routes/+page.svelte
  src/routes/demo/+page.svelte
  src/scss/maplibre-gl-terradraw.scss
  static/assets/plugin-overview.png
  static/assets/plugin-overview.webp
Labels: bug

#74 Fix/when no render mode
  .changeset/shiny-wasps-sell.md
  src/lib/MaplibreTerradrawControl.ts
  src/routes/demo/+page.svelte
Labels: bug

#82 doc: added customization pages to easily add them in the future
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/customise/MapTemplate.svelte
  src/routes/customise/drawing-option/+page.svelte
  src/routes/customise/select-event/+page.svelte
  src/routes/demo/+page.svelte
  static/assets/maplibre-npm-example.txt
Labels: documentation

#83 chore: updated devDependencies.
  .changeset/soft-gorillas-confess.md
  package.json
  pnpm-lock.yaml
Labels: enhancement

#85 doc: fixed sample code becomes serialized string by svelte
  src/routes/customise/MapTemplate.svelte
  src/routes/customise/drawing-option/+page.svelte
  src/routes/customise/select-event/+page.svelte
Labels: bug, documentation

#86 Fix/reset state
  .changeset/large-emus-raise.md
  src/lib/MaplibreTerradrawControl.ts
Labels: bug

#88 doc: added an example of adding geojson as default
  src/routes/+layout.server.ts
  src/routes/customise/add-geojson/+page.svelte
Labels: documentation

#89 fix: fixed bug of NPM example, and added bun package manager
  CONTRIBUTING.md
  src/routes/+page.svelte
  static/assets/maplibre-npm-example.txt
Labels: documentation

#90 doc: renamed customise to examples, and improved UI. add default data for main demo page
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/demo/+page.server.ts
  src/routes/demo/+page.svelte
  src/routes/examples/+page.server.ts
  src/routes/examples/+page.svelte
  src/routes/examples/MapTemplate.svelte
  src/routes/examples/add-geojson/+page.svelte
  src/routes/examples/drawing-option/+page.svelte
  src/routes/examples/select-event/+page.svelte
  static/assets/images/add-geojson.webp
  static/assets/images/customise-draw-option.webp
  static/assets/images/subscribe-selectevent.webp
  static/assets/maplibre-npm-example.txt
Labels: documentation
